/**PERMISSIONS ACTION TYPES */
export const CREATE_PERMISSION = "CREATE_PERMISSION";
export const FETCH_PERMISSIONS = "FETCH_PERMISSIONS";
export const FETCH_PERMISSION = "FETCH_PERMISSION";
export const DELETE_PERMISSION = "DELETE_PERMISSION";
export const EDIT_PERMISSION = "EDIT_PERMISSION";
/**ROLES ACTION TYPES */
export const CREATE_ROLE = "CREATE_ROLE";
export const FETCH_ROLES = "FETCH_ROLES";
export const FETCH_ROLE = "FETCH_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";
export const EDIT_ROLE = "EDIT_ROLE";
/**USERS ACTION TYPES */
export const CREATE_USER = "CREATE_USER";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER = "FETCH_USER";
export const DELETE_USER = "DELETE_USER";
export const EDIT_USER = "EDIT_USER";
/**CAREERS ACTION TYPES */
export const CREATE_CAREER = "CREATE_CAREER";
export const FETCH_CAREERS = "FETCH_CAREERS";
export const FETCH_CAREER = "FETCH_CAREER";
export const DELETE_CAREER = "DELETE_CAREER";
export const EDIT_CAREER = "EDIT_CAREER";
/**EDUCATIONAL_LEVELS ACTION TYPES */
export const CREATE_EDUCATIONAL_LEVEL = "CREATE_EDUCATIONAL_LEVEL";
export const FETCH_EDUCATIONAL_LEVELS = "FETCH_EDUCATIONAL_LEVELS";
export const FETCH_EDUCATIONAL_LEVEL = "FETCH_EDUCATIONAL_LEVEL";
export const DELETE_EDUCATIONAL_LEVEL = "DELETE_EDUCATIONAL_LEVEL";
export const EDIT_EDUCATIONAL_LEVEL = "EDIT_EDUCATIONAL_LEVEL";