/**PERMISSIONS ACTION TYPES */
export const CREATE_PERMISSION = "CREATE_PERMISSION";
export const FETCH_PERMISSIONS = "FETCH_PERMISSIONS";
export const FETCH_PERMISSION = "FETCH_PERMISSION";
export const DELETE_PERMISSION = "DELETE_PERMISSION";
export const EDIT_PERMISSION = "EDIT_PERMISSION";
/**ROLES ACTION TYPES */
